### ISSUE TITLE
Feature: Search

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#11]
### Description
As a user, I'd like to search for kweets, in order to find a specific kweet.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to search for kweets
- [ ] Should be able to search for words used in kweets
- [ ] Should be able to search for users

Also, here are a few points that need to be addressed:

1. Constraint 1: 

### Tasks
- [ ] _TBA_
- [ ] _TBA_
- [ ] _TBA_
