### ISSUE TITLE
Feature: Delete a kwetter

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#2]
### Description
As a user, I'd like to have an option to delete my kweet, in order to undo all my wrongs.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to delete a kweet
- [ ] Should be able to see a warning prompt before deletion

Also, here are a few points that need to be addressed:

1. Constraint 1:

### Tasks
- [ ] Make a endpoint for deleting a kweet
- [ ] Design and implement the UI for deleting a kweet
