### ISSUE TITLE
Feature: Like a kweet

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#3]
### Description
As a user, I'd like to like a kweet, in order to show my appreciation.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to like a kweet

Also, here are a few points that need to be addressed:

1. Constraint 1: A user can only like a kweet once

### Tasks
- [x] Make an endpoint for liking
- [x] Front-end component
