### ISSUE TITLE
Feature: Authentication/authorization

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#4]
### Description
As a guest, I'd like to be able to register an account, in order to begin kwettering.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to make an account with email, username and password

Also, here are a few points that need to be addressed:

1. Constraint 1: Username cannot be longer than 20 characters

### Tasks
- [x] Research third-party options as well as own implementations
- [x] Implement authentication in the front-end
- [x] Implement authentication in the back-end
