### ISSUE TITLE
Feature: Edit profile biography

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#5]
### Description
As a user, I'd like to edit my own profile, in order to update my likings.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to edit profile bio

Also, here are a few points that need to be addressed:

1. Constraint 1: The bio cannot be longer than 140 characters

### Tasks
- [ ] Make an endpoint for editing profile bio
- [ ] Design and implement the UI for editing bio
