### ISSUE TITLE
Feature: Follow a user

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#6]
### Description
As a user, I'd like to follow another user, in order to receive updates from that user.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to follow another user
- [x] Should be able to unfollow another user

Also, here are a few points that need to be addressed:

1. Constraint 1: A user can't follow themselves

### Tasks
- [x] Follow service
- [x] Design and implement the UI for following a user
