### ISSUE TITLE
Feature: Show followers

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#7]
### Description
As a user, I'd like to see the amount of people I follow, in order to get a quick overview.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to see the people they are following
- [x] Should be able to click on one of the followers
- [x] Should be able to see the amount of followers

Also, here are a few points that need to be addressed:

1. Constraint 1: Only shows the pictures of the first 5 followers

### Tasks
- [x] Design and implement the UI for showing followers
