### ISSUE TITLE
Feature: Profile timeline

### ISSUE THREAD

**Issue by RoyAppeldoorn** [RoyAppeldoorn/kwetter#9]
### Description
As a user, I'd like to have a profile timeline, in order to see my own kweets and likes.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to see kweets the user has created
- [ ] Should be able to see the kweets they liked

Also, here are a few points that need to be addressed:

1. Prerequisite: Kwetter service and profile service need to be implemented first

### Tasks
- [ ] Design and implement the UI for profile timeline
